// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbJNrQYjX4DwCWJdTxEgPW5_ZAi9S7lNo',
    appId: '1:71353572223:web:009fa4e21263c5e255184a',
    messagingSenderId: '71353572223',
    projectId: 'promoapp-519fb',
    authDomain: 'promoapp-519fb.firebaseapp.com',
    storageBucket: 'promoapp-519fb.appspot.com',
    measurementId: 'G-CQBV8JWQN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoHgZCEwN5zIZ3xvIGxAEIu33wdxongTY',
    appId: '1:71353572223:android:4df1285639810c4d55184a',
    messagingSenderId: '71353572223',
    projectId: 'promoapp-519fb',
    storageBucket: 'promoapp-519fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldfbqMUsL8lQ65hZVjLDni5fBhMdxxSs',
    appId: '1:71353572223:ios:9b4a734481ca76ff55184a',
    messagingSenderId: '71353572223',
    projectId: 'promoapp-519fb',
    storageBucket: 'promoapp-519fb.appspot.com',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldfbqMUsL8lQ65hZVjLDni5fBhMdxxSs',
    appId: '1:71353572223:ios:9b4a734481ca76ff55184a',
    messagingSenderId: '71353572223',
    projectId: 'promoapp-519fb',
    storageBucket: 'promoapp-519fb.appspot.com',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbJNrQYjX4DwCWJdTxEgPW5_ZAi9S7lNo',
    appId: '1:71353572223:web:6949efd080f7de9255184a',
    messagingSenderId: '71353572223',
    projectId: 'promoapp-519fb',
    authDomain: 'promoapp-519fb.firebaseapp.com',
    storageBucket: 'promoapp-519fb.appspot.com',
    measurementId: 'G-RK8783PK36',
  );

}